name: uniscene
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=py39h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.5.39=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.5=3
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py39h06a4308_0
  - jpeg=9b=0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.10.0.4=0
  - libcurand=10.3.6.39=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.14=0
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.0=h89dd481_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.0.3=0
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.16=h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - pytorch=2.1.1=py3.9_cpu_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cpu
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py39h06a4308_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - altair==5.3.0
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.4.1
    - async-timeout==4.0.3
    - attrs==23.2.0
    - black==23.7.0
    - blinker==1.8.2
    - braceexpand==0.1.7
    - cachetools==5.3.3
    - chardet==5.1.0
    - click==8.1.7
    - clip==1.0
    - cmake==3.29.5.1
    - comm==0.2.2
    - configargparse==1.7
    - contourpy==1.2.1
    - cycler==0.12.1
    - dash==2.18.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - decorator==5.1.1
    - deepspeed==0.10.1
    - descartes==1.1.0
    - docker-pycreds==0.4.0
    - einops==0.8.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fairscale==0.4.13
    - fastjsonschema==2.20.0
    - fire==0.6.0
    - flask==3.0.3
    - fonttools==4.53.0
    - frozenlist==1.4.1
    - fsspec==2024.6.0
    - ftfy==6.2.0
    - gevent==24.2.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - greenlet==3.0.3
    - grpcio==1.66.1
    - hjson==3.1.0
    - huggingface-hub==0.23.4
    - imageio==2.31.1
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.0
    - invisible-watermark==0.2.0
    - ipython==8.18.1
    - ipywidgets==8.1.5
    - itsdangerous==2.2.0
    - jedi==0.19.1
    - joblib==1.4.2
    - jsonschema==4.22.0
    - jsonschema-specifications==2023.12.1
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.5
    - kornia==0.6.9
    - lightning-utilities==0.11.2
    - lit==18.1.7
    - llvmlite==0.43.0
    - markdown==3.7
    - markdown-it-py==3.0.0
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - multidict==6.0.5
    - mypy-extensions==1.0.0
    - natsort==8.4.0
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - ninja==1.11.1.1
    - numba==0.60.0
    - nuscenes-devkit==1.1.11
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.1.105
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - open-clip-torch==2.24.0
    - open3d==0.18.0
    - opencv-python==4.6.0.66
    - packaging==24.1
    - pandas==2.2.2
    - parso==0.8.4
    - pathspec==0.12.1
    - pexpect==4.9.0
    - pillow==10.3.0
    - platformdirs==4.2.2
    - plotly==5.24.1
    - prettytable==3.11.0
    - prompt-toolkit==3.0.47
    - protobuf==3.20.3
    - psutil==5.9.8
    - ptyprocess==0.7.0
    - pudb==2024.1
    - pure-eval==0.2.3
    - py-cpuinfo==9.0.0
    - pyarrow==16.1.0
    - pycocotools==2.0.8
    - pydantic==1.10.16
    - pydeck==0.9.1
    - pygments==2.18.0
    - pyparsing==3.1.2
    - pyquaternion==0.9.9
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.0.1
    - pytz==2024.1
    - pywavelets==1.6.0
    - pyyaml==6.0.1
    - referencing==0.35.1
    - regex==2024.5.15
    - retrying==1.3.4
    - rich==13.7.1
    - rpds-py==0.18.1
    - safetensors==0.4.3
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - sentencepiece==0.2.0
    - sentry-sdk==2.5.1
    - setproctitle==1.3.3
    - shapely==1.8.5.post1
    - six==1.16.0
    - smmap==5.0.1
    - stack-data==0.6.3
    - streamlit==1.35.0
    - sympy==1.13.1
    - tenacity==8.4.0
    - tensorboard==2.17.1
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - timm==1.0.3
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.1
    - torch==2.5.1+cu121
    - torchaudio==2.5.1+cu121
    - torchdata==0.6.1
    - torchmetrics==1.4.0.post0
    - torchvision==0.20.1+cu121
    - tornado==6.4.1
    - tqdm==4.66.4
    - traitlets==5.14.3
    - transformers==4.19.1
    - triton==3.1.0
    - tzdata==2024.1
    - urllib3==1.26.18
    - urwid==2.6.14
    - urwid-readline==0.14
    - wandb==0.17.1
    - watchdog==4.0.1
    - wcwidth==0.2.13
    - webdataset==0.2.86
    - werkzeug==3.0.4
    - widgetsnbextension==4.0.13
    - xformers==0.0.22
    - yarl==1.9.4
    - zipp==3.20.2
    - zope-event==5.0
    - zope-interface==6.4.post2
