name: occ2lidar
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py38h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.5=3
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.10.1.7=0
  - libcurand=10.3.6.82=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.0.14=h5eee18b_0
  - pillow=10.3.0=py38h5eee18b_0
  - pip=24.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - pytorch=1.13.1=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.13.1=py38_cu117
  - torchvision=0.14.1=py38_cu117
  - typing_extensions=4.11.0=py38h06a4308_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aliyun-python-sdk-core==2.15.2
      - aliyun-python-sdk-kms==2.16.5
      - apptools==5.3.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - backcall==0.2.0
      - blessed==1.20.0
      - blinker==1.8.2
      - cachetools==5.5.0
      - ccimport==0.4.3
      - cffi==1.17.1
      - chamferdist==1.0.3
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - configobj==5.0.9
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==43.0.1
      - cumm-cu117==0.4.11
      - cycler==0.12.1
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dda3d-cuda==0.0.0
      - decorator==5.1.1
      - descartes==1.1.0
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - envisage==7.0.3
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - filelock==3.14.0
      - fire==0.6.0
      - flash-attn==2.6.3
      - flask==3.0.3
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.34.0
      - google-auth-oauthlib==1.0.0
      - gpustat==1.1.1
      - grpcio==1.66.1
      - huggingface-hub==0.24.5
      - imageio==2.34.2
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.3
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jaxtyping==0.2.19
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.5
      - lark==1.1.9
      - lazy-loader==0.4
      - lightning-utilities==0.11.7
      - llvmlite==0.41.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mayavi==4.8.2
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.4
      - model-index==0.1.11
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1.1
      - numba==0.58.1
      - nuscenes-devkit==1.1.11
      - nvidia-ml-py==12.560.30
      - oauthlib==3.2.2
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.1
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.1
      - pandas==2.0.3
      - parso==0.8.4
      - pccm==0.4.14
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.2.2
      - plotly==5.24.1
      - portalocker==2.10.1
      - prompt-toolkit==3.0.47
      - protobuf==5.27.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pybind11==2.13.1
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pyface==8.0.0
      - pygments==2.18.0
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyvirtualdisplay==3.0
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - referencing==0.35.1
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.4.2
      - rpds-py==0.20.0
      - rsa==4.9
      - safetensors==0.4.4
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - shapely==1.8.5.post1
      - sharedarray==3.2.4
      - six==1.16.0
      - smmap==5.0.1
      - spconv-cu117==2.3.6
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - timm==1.0.8
      - tomli==2.0.1
      - torch-scatter==2.1.1+pt113cu117
      - torchmetrics==1.4.3
      - tqdm==4.65.2
      - traitlets==5.14.3
      - traits==6.4.3
      - traitsui==8.0.0
      - triton==3.0.0
      - typeguard==4.3.0
      - tzdata==2024.1
      - urllib3==1.26.20
      - vtk==9.3.1
      - wandb==0.17.7
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - yapf==0.40.2
      - zipp==3.20.0
